@localURL = http://localhost:5150

GET {{localURL}}/weatherforecast/
Accept: application/json

###

GET {{localURL}}/api/books/
Accept: application/json

###
GET {{localURL}}/api/books/5
Accept: application/json


###
POST {{localURL}}/api/books
Content-Type: application/json
{
  "title": "1984",
  "author": "George Orwell",
  "yearPublished": 1949
}

###
PUT {{localURL}}/api/books/5
Content-Type: application/json
{
  "title": "This is a test",
  "author": "George Orwell",
  "yearPublished": 1949
}

###
DELETE {{localURL}}/api/books/5

###
GET {{localURL}}/api/PersonalCMSV2/models
Accept: application/json


###
GET {{localURL}}/api/PersonalCMSV2/model/localizationToken
Accept: application/json

###
GET {{localURL}}/api/PersonalCMSV2/entries/
Accept: application/json

###
GET {{localURL}}/api/PersonalCMSV2/entries/13beba48-4da1-4f0a-85da-2416c8fbb94b
Accept: application/json

